m15a/flake-awesome-neovim-plugins

bin/update-vim-plugins
overrides.nix
pkgs/vim-plugins.nix

Add missing licenses

---

README.md
blacklist.txt
manifest.txt
overrides.nix
pkgs/vim-plugins.nix

Remove some plugins

---

README.md
manifest.txt
overrides.nix
pkgs/vim-plugins.nix

Implement another part of #17.

fix: add missing dependencies (part 2)

---

README.md
assets/README_header.md

chore!: rename project to nixpkgs-vim-extra-plugins

---

README.md
assets/README_footer.md
bin/update-vim-plugins
pkgs/update-vim-plugins.nix

Rewrite spec parser

---

bin/update-vim-plugins
manifest.txt

Fix awesome-neovim readme parser

---

overrides.nix

fix: add missing dependencies (part 3)

---

overrides.nix

fix(mdeval-nvim): add missing buildInputs

---

overrides.nix

fix(rest-nvim): add missing deps and fix jq path

---

README.md
manifest.txt
overrides.nix
pkgs/vim-plugins.nix

fix(navigator-lua): add missing dependencies

---

overrides.nix

fix(go-nvim): add missing dependency

---

README.md
blacklist.txt
flake.lock
manifest.txt
overrides.nix
pkgs/vim-plugins.nix

Remove officially maintained plugins

---

README.md
manifest.txt
pkgs/vim-plugins.nix

feat: add kmonad/kmonad-vim

---

README.md
manifest.txt
overrides.nix
pkgs/vim-plugins.nix

Close #57 
- coc-extensions/coc-svelte
- evanleck/vim-svelte
- github/copilot.vim
- iamcco/coc-tailwindcss
- leafOfTree/vim-svelte-plugin
- nvim-telescope/telescope-media-files.nvim
- rodrigore/coc-tailwind-intellisense
- thaerkh/vim-workspace
- themaxmarchuk/tailwindcss-colors.nvim

feat: add various plugins

---

flake.nix

chore: use new naming convention of flake attributes

---

README.md
manifest.txt
pkgs/vim-plugins.nix

See https://github.com/rockerBOO/awesome-neovim/pull/512.

fix(nvim-colorizer-lua): remove norcalli/nvim-colorizer.lua

---

.github/workflows/awesome-neovim.yml
.github/workflows/update-plugins.yml

Fix https://github.com/m15a/nixpkgs-vim-extra-plugins/runs/7812516392

fix(github): use PAT as api rate limit sometimes exceeds

---

bin/update-vim-plugins

Just improved docstrings/comments and done refactoring some functions in `bin/update-vim-plugins`.

refactor: update-vim-plugins

---

.github/workflows/awesome-neovim.yml
.github/workflows/update-plugins.yml
CHANGELOG.md
assets/README_footer.md
bin/update-vim-plugins
manifest.txt
pkgs/update-vim-plugins.nix

Support sourcehut

---

README.md
assets/README_header.md

Path to overlay has changed since ee9b83cbb461081157ed3e47e3bd8077b695a7b8.

doc: fix overlay path

---

.github/workflows/check.yml

chore(github): use cachix for ci

---

README.md
manifest.txt
pkgs/vim-plugins.nix

See https://github.com/rockerBOO/awesome-neovim/pull/527.

fix(autoclose-nvim): update owner's name

---

README.md
manifest.txt
pkgs/vim-plugins.nix

See https://github.com/rockerBOO/awesome-neovim/issues/531.

fix(github-vscode-theme-nvim): remove kaiuri/github-vscode-theme.nvim

---

flake.nix

https://github.com/NixOS/nixpkgs/pull/192681

fix: deprecated runCommandNoCC

---

overrides.nix

https://github.com/ellisonleao/glow.nvim/pull/80

fix(glow-nvim): remove deprecated patch

---

README.md
manifest.txt
pkgs/vim-plugins.nix

Close #91 
See https://github.com/rockerBOO/awesome-neovim/pull/560

fix(ataraxis-lua): remove github repo

---

CHANGELOG.md
nix/awesome-neovim-plugins.nix
nix/overrides.nix
nix/utils.nix

fix: rename attr name of repos with identical name

---

CHANGELOG.md
README.md
nix/overrides.nix

feat: support nvim-treesitter passthru attrs

---

nix/overrides.nix

Add dependencies for LSP-related plugins

---

tools/update.fnl

fix: drop non-plugin repositories

---

CHANGELOG.md
nix/overrides.nix

fix(treesitter): add deps for treesitter consumers

---

nix/overrides.nix

fix(telescope): add deps for telescope consumers

---

nix/awesome-neovim-plugins.nix
nix/utils.nix

fix: rename plugins having meaningless repo name

---

CHANGELOG.md
data/plugins-info/awesome-neovim.json
data/plugins-info/extra-fetchers.json
nix/awesome-neovim-plugins.nix
nix/ci.nix
nix/overrides.nix
tools/update.fnl

Support auto-update of sniprun Rust binary

---

tools/update.fnl

fix(update.fnl): update extra hashes with two stages

---

nix/overrides.nix

https://github.com/rockerBOO/awesome-neovim/pull/1308
Fix the build failure: https://github.com/m15a/flake-awesome-neovim-plugins/actions/runs/10753120021/job/29822206807#step:6:27

fix: remove mind.nvim override

---

CHANGELOG.md
data/plugins/awesome-neovim.json
data/plugins/extra-fetchers.json
nix/awesome-neovim-plugins.nix
nix/overrides.nix

fix(sniprun): use cargoHash instead of deprecated cargoSha256

---

tools/update.fnl

fix: parse GitLab namespace

---

flake.lock
flake.nix
nix/ci.nix
treefmt.nix

ci: use treefmt-nix
